[package]
name = "rustypaste"
version = "0.6.3"
edition = "2021"
description = "A minimal file upload/pastebin service"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/orhun/rustypaste"
repository = "https://github.com/orhun/rustypaste"
keywords = ["paste", "pastebin", "upload"]
categories = ["web-programming::http-server"]
include = ["src/**/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
actix-web = { version = "4.0.1", features = ["rustls"] }
actix-multipart = "0.4.0"
actix-files = "0.6.0"
awc = "3.0.0"
env_logger = "0.9.0"
log = "0.4.14"
serde = "1.0.136"
futures-util = "0.3.21"
petname = "1.1.2"
rand = "0.8.5"
dotenv = "0.15.0"
url = "2.2.2"
mime = "0.3.16"
regex = "1.5.4"
serde_regex = "1.1.0"
lazy-regex = "2.2.1"
humantime = "2.1.0"
humantime-serde = "1.1.1"
glob = "0.3.0"
ring = "0.16.20"
hotwatch = "0.4.5"

[dependencies.config]
version = "0.12.0"
default-features = false
features = ["toml", "yaml"]

[dependencies.byte-unit]
version = "4.0.13"
features = ["serde"]

[dependencies.infer]
version = "0.7.0"
default-features = false

[dev-dependencies]
actix-rt = "1.1.1"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
